import type {
  ProductCategory,
  Product,
  Industry,
  GalleryItem,
  TeamMember,
  Testimonial,
  Faq,
} from "@/types";

export const fallbackProductCategories: ProductCategory[] = [
  {
    id: "cat-1",
    slug: "chair-covers",
    name: "Chair Covers",
    shortDescription: "Tailored fitted covers for banquet, folding, and specialty chairs.",
    longDescription: "Our chair covers are precision-crafted to fit your specific chair models perfectly. Available in a wide range of fabrics, colors, and with custom branding options including embroidery and screen printing.",
    heroImageUrl: "/images/products/chair-covers.jpg",
    featuredImageUrl: "/images/products/chair-covers.jpg",
    isFeatured: true,
    sortOrder: 1,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "cat-2",
    slug: "table-covers",
    name: "Table Covers",
    shortDescription: "Custom tablecloths, toppers, and fitted table covers for any size.",
    longDescription: "From cocktail tables to banquet rounds, our table covers are made to your exact dimensions. Choose from premium fabrics that resist stains and wrinkling.",
    heroImageUrl: "/images/products/table-covers.jpg",
    featuredImageUrl: "/images/products/table-covers.jpg",
    isFeatured: true,
    sortOrder: 2,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "cat-3",
    slug: "podium-covers",
    name: "Podium & Lectern Covers",
    shortDescription: "Branded podium covers for presentations and ceremonies.",
    longDescription: "Make every presentation on-brand with our custom podium and lectern covers. Designed for easy setup and removal.",
    heroImageUrl: "/images/products/podium-covers.jpg",
    featuredImageUrl: "/images/products/podium-covers.jpg",
    isFeatured: true,
    sortOrder: 3,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "cat-4",
    slug: "bar-covers",
    name: "Bar & Counter Covers",
    shortDescription: "Fitted covers for bars, reception counters, and service stations.",
    longDescription: "Transform your bar and counter areas with custom-fitted covers that protect surfaces while reinforcing your brand.",
    heroImageUrl: "/images/products/bar-covers.jpg",
    featuredImageUrl: "/images/products/bar-covers.jpg",
    isFeatured: true,
    sortOrder: 4,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "cat-5",
    slug: "equipment-covers",
    name: "Equipment Covers",
    shortDescription: "Protective covers for AV equipment, registers, and specialty gear.",
    longDescription: "Keep your valuable equipment dust-free and protected with custom covers designed for your specific gear.",
    heroImageUrl: "/images/products/equipment-covers.jpg",
    featuredImageUrl: "/images/products/equipment-covers.jpg",
    isFeatured: false,
    sortOrder: 5,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "cat-6",
    slug: "trade-show-covers",
    name: "Trade Show & Display Covers",
    shortDescription: "Branded covers for booths, displays, and exhibition elements.",
    longDescription: "Stand out at your next trade show with branded covers for booth elements, display cases, and demo stations.",
    heroImageUrl: "/images/products/trade-show-covers.jpg",
    featuredImageUrl: "/images/products/trade-show-covers.jpg",
    isFeatured: false,
    sortOrder: 6,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "cat-7",
    slug: "outdoor-covers",
    name: "Outdoor & Patio Covers",
    shortDescription: "Weather-resistant covers for outdoor furniture and equipment.",
    longDescription: "Protect your outdoor investment with weather-resistant covers designed for Southern California conditions.",
    heroImageUrl: "/images/products/outdoor-covers.jpg",
    featuredImageUrl: "/images/products/outdoor-covers.jpg",
    isFeatured: false,
    sortOrder: 7,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
];

export const fallbackProducts: Product[] = [
  {
    id: "prod-1",
    categoryId: "cat-1",
    slug: "banquet-chair-covers",
    name: "Banquet Chair Covers",
    summary: "Fitted covers for standard banquet and Chiavari chairs.",
    description: "Our banquet chair covers are the industry standard for hotels, country clubs, and event venues. Each cover is tailored to your specific chair model for a flawless fit.",
    useCases: ["Hotel ballrooms", "Wedding venues", "Country clubs", "Cruise lines", "Conference centers"],
    availableFabrics: ["Polyester", "Spandex", "Satin", "Damask", "Linen-blend"],
    availableColors: ["White", "Ivory", "Black", "Navy", "Burgundy", "Custom color match"],
    brandingOptions: ["Embroidered logo", "Screen-printed monogram", "Sash accent", "Pleated skirt option"],
    imageUrl: "/images/products/chair-covers.jpg",
    isActive: true,
    sortOrder: 1,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "prod-2",
    categoryId: "cat-1",
    slug: "folding-chair-covers",
    name: "Folding Chair Covers",
    summary: "Covers for metal and plastic folding chairs used at events.",
    description: "Transform utilitarian folding chairs into elegant seating with our custom covers.",
    useCases: ["Outdoor events", "Tent weddings", "Corporate functions", "Community centers", "Rental companies"],
    availableFabrics: ["Polyester", "Spandex", "Microfiber"],
    availableColors: ["White", "Ivory", "Black", "Custom color match"],
    brandingOptions: ["Printed logo", "Embroidered text", "Ribbon tie accent"],
    imageUrl: null,
    isActive: true,
    sortOrder: 2,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
];

export const fallbackIndustries: Industry[] = [
  {
    id: "ind-1",
    slug: "hospitality",
    name: "Hotels & Resorts",
    summary: "Elevate guest experiences with branded covers that reflect your property's quality.",
    description: "From the ballroom to the boardroom, hotels and resorts trust CoverCo for chair covers, table linens, podium drapes, and bar covers.",
    heroImageUrl: "/images/industries/hospitality.jpg",
    benefits: ["Commercial-laundry durable fabrics", "Rapid turnaround for large orders", "Color-matching to brand standards", "Setup-friendly designs", "Inventory management support"],
    recommendedCategories: ["Chair Covers", "Table Covers", "Podium Covers", "Bar Covers"],
    sortOrder: 1,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "ind-2",
    slug: "sports-venues",
    name: "Sports Venues & Stadiums",
    summary: "Dress premium seating and VIP areas with team-branded covers.",
    description: "Sports venues choose CoverCo for luxury box seating, VIP clubs, press conference podiums, and event hospitality areas.",
    heroImageUrl: "/images/industries/sports-venues.jpg",
    benefits: ["Heavy-duty fabrics for high traffic", "Team color matching", "Sponsor logo integration", "Quick-change designs", "Fire-retardant options available"],
    recommendedCategories: ["Chair Covers", "Table Covers", "Equipment Covers"],
    sortOrder: 2,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "ind-3",
    slug: "convention-centers",
    name: "Convention Centers",
    summary: "Furnish flexible event spaces with versatile, durable cover solutions.",
    description: "Convention centers need covers that work across hundreds of different event configurations.",
    heroImageUrl: "/images/industries/convention-centers.jpg",
    benefits: ["Fits standard rental inventory", "Rapid install/remove for quick turnovers", "Neutral and custom color options", "Volume pricing for large orders", "Coordinated sets for consistent look"],
    recommendedCategories: ["Chair Covers", "Table Covers", "Podium Covers", "Trade Show Covers"],
    sortOrder: 3,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "ind-4",
    slug: "casinos",
    name: "Casinos & Gaming",
    summary: "Premium covers for player seating, VIP areas, and event spaces.",
    description: "Casinos demand the highest standard of presentation.",
    heroImageUrl: "/images/industries/hospitality.jpg",
    benefits: ["Luxury appearance for premium positioning", "Stain-resistant fabric options", "Custom gaming-themed designs", "Rapid replacement program", "Discrete logo placement options"],
    recommendedCategories: ["Chair Covers", "Table Covers", "Bar Covers"],
    sortOrder: 4,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "ind-5",
    slug: "restaurants",
    name: "Restaurants & Dining",
    summary: "Refresh dining rooms with custom covers that reinforce your brand.",
    description: "From fine dining to casual concepts, restaurants use our covers to protect seating investments.",
    heroImageUrl: "/images/industries/restaurants.jpg",
    benefits: ["Easy-clean fabric options", "Seasonal refresh programs", "Logo integration for brand reinforcement", "Slip-resistant fitted designs", "Cost-effective alternative to reupholstery"],
    recommendedCategories: ["Chair Covers", "Table Covers", "Bar Covers"],
    sortOrder: 5,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "ind-6",
    slug: "universities",
    name: "Universities & Institutions",
    summary: "Covers for ceremony seating, lecture halls, and event spaces.",
    description: "Academic institutions rely on CoverCo for commencement ceremony chair covers.",
    heroImageUrl: "/images/industries/universities.jpg",
    benefits: ["Procurement-friendly quoting", "Volume academic pricing", "Ceremony-specific designs", "Multi-department coordination", "Durable for year-round use"],
    recommendedCategories: ["Chair Covers", "Podium Covers", "Table Covers"],
    sortOrder: 6,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "ind-7",
    slug: "cruise-lines",
    name: "Cruise Lines",
    summary: "Marine-grade covers designed for the unique demands of shipboard environments.",
    description: "Cruise lines face unique challenges: salt air, UV exposure, space constraints, and rapid turnaround.",
    heroImageUrl: "/images/industries/cruise-lines.jpg",
    benefits: ["Marine-grade UV-stable fabrics", "Compact storage designs", "Rapid deployment for port turnaround", "Salt-air resistant materials", "IMO fire safety compliant options"],
    recommendedCategories: ["Chair Covers", "Table Covers", "Outdoor Covers", "Bar Covers"],
    sortOrder: 7,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
];

export const fallbackGalleryItems: GalleryItem[] = [
  {
    id: "gal-1",
    title: "Hotel Ballroom Transformation",
    slug: "hotel-ballroom",
    imageUrl: "/images/gallery/ballroom.jpg",
    altText: "Elegant hotel ballroom with white chair covers and floor-length tablecloths",
    caption: "Complete ballroom setup for 500-guest gala",
    beforeAfterType: "single",
    productCategoryId: null,
    industryId: null,
    tags: ["hotel", "ballroom", "chair covers", "table covers", "white"],
    sortOrder: 1,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "gal-2",
    title: "Outdoor Patio Before",
    slug: "outdoor-patio-before",
    imageUrl: "/images/gallery/patio-before.jpg",
    altText: "Weathered outdoor patio furniture before cover installation",
    caption: "Patio furniture showing UV damage before treatment",
    beforeAfterType: "before",
    productCategoryId: null,
    industryId: null,
    tags: ["outdoor", "patio", "before", "restoration"],
    sortOrder: 4,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "gal-3",
    title: "Outdoor Patio After",
    slug: "outdoor-patio-after",
    imageUrl: "/images/gallery/patio-after.jpg",
    altText: "Refreshed outdoor patio with fitted furniture covers",
    caption: "Same space with new fitted covers and coordinated cushions",
    beforeAfterType: "after",
    productCategoryId: null,
    industryId: null,
    tags: ["outdoor", "patio", "after", "restoration"],
    sortOrder: 5,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "gal-4",
    title: "Sports Stadium Luxury Box",
    slug: "stadium-luxury-box",
    imageUrl: "/images/gallery/stadium.jpg",
    altText: "Premium stadium seating area with team-colored covers",
    caption: "NFL luxury box with team-branded fitted covers",
    beforeAfterType: "single",
    productCategoryId: null,
    industryId: null,
    tags: ["sports", "stadium", "chair covers", "branding"],
    sortOrder: 6,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "gal-5",
    title: "Convention Center Setup",
    slug: "convention-center",
    imageUrl: "/images/gallery/convention.jpg",
    altText: "Massive convention hall with uniform chair covers on thousands of seats",
    caption: "50,000-seat general session with coordinated covers",
    beforeAfterType: "single",
    productCategoryId: null,
    industryId: null,
    tags: ["convention", "large scale", "chair covers", "gray"],
    sortOrder: 7,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "gal-6",
    title: "University Commencement",
    slug: "university-commencement",
    imageUrl: "/images/gallery/commencement.jpg",
    altText: "University commencement ceremony with white chair covers",
    caption: "Spring commencement with 3,000 white chair covers",
    beforeAfterType: "single",
    productCategoryId: null,
    industryId: null,
    tags: ["university", "ceremony", "chair covers", "white"],
    sortOrder: 10,
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01",
  },
];

export const fallbackTeamMembers: TeamMember[] = [
  {
    id: "team-1",
    name: "Michael Torres",
    title: "Founder & CEO",
    bio: "Michael founded CoverCo in 1989 after recognizing the need for quality fitted covers in the San Diego hospitality market.",
    imageUrl: null,
    sortOrder: 1,
    createdAt: "2024-01-01",
  },
  {
    id: "team-2",
    name: "Jennifer Walsh",
    title: "VP of Operations",
    bio: "Jennifer oversees production, quality control, and logistics.",
    imageUrl: null,
    sortOrder: 2,
    createdAt: "2024-01-01",
  },
  {
    id: "team-3",
    name: "David Chen",
    title: "Director of Sales",
    bio: "David leads our account management team, working directly with hospitality buyers.",
    imageUrl: null,
    sortOrder: 3,
    createdAt: "2024-01-01",
  },
  {
    id: "team-4",
    name: "Sarah Martinez",
    title: "Design & Customization Lead",
    bio: "Sarah manages our design studio, helping clients select fabrics, colors, and branding options.",
    imageUrl: null,
    sortOrder: 4,
    createdAt: "2024-01-01",
  },
];

export const fallbackTestimonials: Testimonial[] = [
  {
    id: "test-1",
    name: "Robert Kim",
    company: "Harbor View Hotel & Resort",
    role: "Director of Events",
    quote: "CoverCo has been our go-to cover supplier for 12 years. Their quality is unmatched, and their turnaround time saves us every busy season.",
    imageUrl: null,
    sortOrder: 1,
    createdAt: "2024-01-01",
  },
  {
    id: "test-2",
    name: "Amanda Foster",
    company: "Pacific Cruise Lines",
    role: "Procurement Manager",
    quote: "We outfitted three ships with CoverCo covers last year. The marine-grade fabric holds up beautifully at sea.",
    imageUrl: null,
    sortOrder: 2,
    createdAt: "2024-01-01",
  },
  {
    id: "test-3",
    name: "James Rodriguez",
    company: "Desert Palm Casino Resort",
    role: "VP of Hospitality",
    quote: "When we needed 2,000 chair covers in our custom burgundy with gold embroidery, CoverCo delivered on time and on budget.",
    imageUrl: null,
    sortOrder: 3,
    createdAt: "2024-01-01",
  },
];

export const fallbackFaqs: Faq[] = [
  {
    id: "faq-1",
    question: "What information do I need to provide for a quote?",
    answer: "To provide an accurate quote, we need: the type and quantity of covers, item dimensions or model numbers, fabric and color preferences, any branding requirements, your timeline, and delivery location.",
    category: "Ordering",
    sortOrder: 1,
    createdAt: "2024-01-01",
  },
  {
    id: "faq-2",
    question: "How long does production typically take?",
    answer: "Standard production time is 3-4 weeks from approved order. Rush orders can often be accommodated for an additional fee.",
    category: "Ordering",
    sortOrder: 2,
    createdAt: "2024-01-01",
  },
];
