import { Inter } from "next/font/google";
import "../scss/globals.scss";
import styles from "../scss/Home.module.scss"
import Navigation from "../components/Navigation/Navigation";
import Footer from "../components/Footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <main className={styles.content}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
